hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
management:
    security:
        enabled: false
server:
    port: 8882
spring:
    rabbitmq:
        host: localhost
        port: 5672
